
services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myvoleipass
      MYSQL_DATABASE: algaida_volei_club
      MYSQL_USER: volei
      MYSQL_PASSWORD: myvoleipass
    ports:
      - "3307:3306"  # Cambia a 3306 si no usas MySQL local fuera de Docker
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect="SET NAMES utf8mb4"


  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db
    restart: always

volumes:
  db_data:
